language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - env: CC_ACTUAL=gcc-4.9 CXX_ACTUAL=g++-4.9
      compiler: gcc
      os: linux
    - env: CC_ACTUAL=clang-3.7 CXX_ACTUAL=clang++-3.7
      compiler: clang
      os: linux

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-key adv --fetch-keys http://llvm.org/apt/llvm-snapshot.gpg.key
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main'
  - sudo apt-get -qq update
  - sudo apt-get -qq -f -y install libwxgtk3.0-dev:i386 libsoundtouch-dev:i386 libaio-dev:i386 libasound2-dev:i386 libgl1-mesa-dev:i386 liblzma-dev:i386 libpng12-dev:i386 libxext-dev:i386 portaudio19-dev:i386
# Some stuff doesn't auto include itself with gtk2. So just throw in everything.
  - sudo apt-get -qq -f -y install libgtk2.0-dev:i386 gir1.2-gtk-2.0:i386 libglib2.0-dev:i386 libgdk-pixbuf2.0-dev:i386 libpango1.0-dev:i386 libatk1.0-dev:i386 libcairo2-dev:i386 gir1.2-atk-1.0:i386 gir1.2-freedesktop:i386 gir1.2-gdkpixbuf-2.0:i386 gir1.2-glib-2.0:i386 gir1.2-pango-1.0:i386 libgirepository-1.0-1:i386
  - sudo apt-get -qq -f -y install libsdl2-dev:i386 libpulse-dev:i386
  - sudo apt-get -f -y install gcc-4.9-multilib g++-4.9-multilib clang-3.7

before_script:
# "Install" libpng++-dev. Mwahahahaha. Well, once it's added to 3rdparty.
#  - cp -r 3rdparty/png++ plugins/GSdx
  - mkdir build && cd build
script:
  - export CC=$CC_ACTUAL CXX=$CXX_ACTUAL
  - cmake -DCMAKE_TOOLCHAIN_FILE=cmake/linux-compiler-i386-multilib.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_REPLAY_LOADERS=TRUE -DCMAKE_BUILD_PO=FALSE ..
# How many? Dunno.
  - make -j4 install
