version: 0.0.{build}

environment:
  matrix:
  - VisualStudioVersion: 12.0
  - VisualStudioVersion: 14.0

platform: Win32

build:
  parallel: true
  project: buildbot.xml

configuration:
  - ReleaseAll
  - DebugAll

branches:
  only:
    - appveyor

init:
  # Use CRLF line endings on Windows.
  - git config --global core.autocrlf true

install:
  - ps: $env:gitrev=git describe --tags
  - ps: Update-AppveyorBuild -Version "$env:gitrev-$env:appveyor_repo_branch-$env:appveyor_build_number"
after_build:
  - type NUL > bin\portable.ini
  - set FOLDER_NAME=pcsx2-%version%-%platform%-%configuration%
  - rename bin %FOLDER_NAME%
  - 7z a -mx9 %FOLDER_NAME%.7z %FOLDER_NAME%

test: off

artifacts:
  - path: $(FOLDER_NAME).7z
    name: $(FOLDER_NAME)
