version: 0.0.{build}

platform: Win32

build:
  parallel: true
  project: buildbot.xml

configuration: ReleaseAll

branch:
  only:
    - appveyor

init:
  - ps: Update-AppveyorBuild -Version "v1.3.1-$env:appveyor_build_number-$env:appveyor_repo_branch-g$($env:appveyor_repo_commit.substring(0,7))"
  # Use CRLF line endings on Windows.
  - git config --global core.autocrlf true

before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%

after_build:
  - type NUL > bin\portable.ini
  - set FOLDER_NAME=pcsx2-%APPVEYOR_BUILD_VERSION%-%PLATFORM%
  - rename bin %FOLDER_NAME%
  - 7z a %FOLDER_NAME%.7z %FOLDER_NAME%

test: off

artifacts:
  - path: $(FOLDER_NAME).7z
    name: $(FOLDER_NAME)
